import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import { Input } from "@/components/ui/input";
import SearchIcon from "@/components/icons/search";
import MountainIcon from "@/components/icons/mountain";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-gray-100 dark:bg-gray-800 py-4 px-4 md:px-6">
          <div className="container mx-auto flex items-center justify-between">
            <Link className="flex items-center gap-2" href="#">
              <MountainIcon className="h-6 w-6" />
              <span className="text-lg font-bold">Web Development Hub</span>
            </Link>
            <div className="flex items-center gap-4">
              <form className="relative">
                <SearchIcon className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-500 dark:text-gray-400" />
                <Input
                  className="pl-10 pr-4 py-2 rounded-md bg-white dark:bg-gray-950 dark:text-gray-50 focus:outline-none focus:ring-1 focus:ring-gray-500 dark:focus:ring-gray-300"
                  placeholder="Search resources..."
                  type="search"
                />
              </form>
            </div>
          </div>
        </header>
        {children}
        <footer className="bg-gray-100 dark:bg-gray-800 py-6 px-4 md:px-6">
          <div className="container mx-auto flex items-center justify-between">
            <p className="text-sm text-gray-500 dark:text-gray-400">
              © 2024 Web Development Hub. All rights reserved.
            </p>
            <div className="flex items-center gap-4" />
          </div>
        </footer>
      </body>
    </html>
  );
}
